import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { 
  User, 
  Role, 
  UserRole, 
  Organization, 
  OrganizationLocation,
  PurchaseOrder,
  PurchaseOrderItem,
  Supplier,
  InventoryItem,
  StockMovement,
  StockTransfer,
  StockTransferItem,
  Recipe,
  RecipeIngredient,
  ProductionPlan,
  ProductionPlanItem,
  KitchenOrder,
  KitchenOrderItem,
  KitchenStation,
  KitchenEquipment,
  Customer,
  Order,
  OrderItem,
  MenuItem,
  Payment
} from './entities';

@Module({
  imports: [
    ConfigModule,
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({
        type: 'postgres',
        host: configService.get('DB_HOST', 'localhost'),
        port: configService.get('DB_PORT', 5432),
        username: configService.get('DB_USERNAME', 'postgres'),
        password: configService.get('DB_PASSWORD', 'password'),
        database: configService.get('DB_DATABASE', 'restaurant_crm'),
        entities: [
          User,
          Role,
          UserRole,
          Organization,
          OrganizationLocation,
          PurchaseOrder,
          PurchaseOrderItem,
          Supplier,
          InventoryItem,
          StockMovement,
          StockTransfer,
          StockTransferItem,
          Recipe,
          RecipeIngredient,
          ProductionPlan,
          ProductionPlanItem,
          KitchenOrder,
          KitchenOrderItem,
          KitchenStation,
          KitchenEquipment,
          Customer,
          Order,
          OrderItem,
          MenuItem,
          Payment,
        ],
        synchronize: configService.get('NODE_ENV') === 'development',
        logging: configService.get('DB_LOGGING', false),
        ssl: configService.get('NODE_ENV') === 'production',
        autoLoadEntities: true,
      }),
      inject: [ConfigService],
    }),
  ],
  exports: [TypeOrmModule],
})
export class DatabaseModule {}